GAME_INSTRUCTIONS = (
    "PLACING PARTS ON THE PLAYFIELD \n"
    "Click on any part in the Parts Bin and move it onto the playfield. Click AGAIN to set the part down! If a red 'X' appears over the part, you have set it too close to another part."
    "\n\nPARTS BIN\n"
    "Radio - Shows or hides the Control Panel on the left.\n"
    "Green Flag - Run the puzzle.\n"
    "Wrench - This brings up Main Menu and shows you that you're in Puzzle Play.\n"
    "Part - The part itself.\n"
    "Index - Number of this part available.\n"
    "Arrows - Scroll through the parts in the Parts Bin.\n"
    "Tree - Brings up and puts away the scenery.\n"
    "\n\nHANDLES\n"
    "Every part in the game comes with two or more \"Handles\". These handy little pictures are your key to controlling the part and the role it plays within the puzzle. To check out the Handles for any part, just pull out of the Parts Bin and drop it on the playfield. Then set your cursor over the part. There's a complete list of Handles below, including a few that you'll only see when you're building puzzles in Professor Tim's Workshop.\n"
    "\n"
    "RECYCLE HANDLE\n"
    "Click on the trash can to put the part back in the Parts Bin.\n"
    "\n"
    "FLIP HANDLE\n"
    "These curved arrows allow you to flip the part. Some parts can be flipped several different ways.\n"
    "\n"
    "SIZE HANDLE\n"
    "This double arrow means the part can be stretched or shrunk when you click on the arrow and drag the cursor. Click the cursor a second time when the part has been stretched to the designated length.\n"
    "\n"
    "PROGRAMMING HANDLE\n"
    "This little computer handle means the part is programmable. There are twelve programmable parts in the game. Click on the computer handle to bring up a window that will let you set the quantity, appearance, behavior, or state of the selected part. (See the Programmable Parts section on page 12 for details.)\n"
    "\n"
    "INFO HANDLE\n"
    "This magnifying glass handle gives you information about any part, including how the part works and ways of using it."
    "\n Beware that not every object is movable or interactable in the level!"
)