GAME_INSTRUCTIONS = (
    "PLACING PARTS ON THE PLAYFIELD \n"
    "Click on any part in the Parts Bin and move it onto the playfield. Click AGAIN to set the part down! If a red 'X' appears over the part, you have set it too close to another part."
    "\n\nPARTS BIN (right side)\n"
    "Radio (top right) - Shows or hides the Control Panel on the left.\n"
    "Green Flag (top left) - Run the puzzle.\n"
    "Wrench (top middle below radio and green flag) - This brings up Main Menu and shows you that you're in Puzzle Play.\n"
    "Parts - All parts available for use.\n"
    "Indices - Numbers of the parts available.\n"
    "Arrows (bottom left) - Scroll through the parts in the Parts Bin.\n"
    "Tree (bottom right) - Brings up and puts away the scenery.\n"
    "\n\nHANDLES\n"
    "Every part in the game comes with two or more \"Handles\". These handy little pictures are your key to controlling the part and the role it plays within the puzzle. To check out the Handles for any part, just pull out of the Parts Bin and drop it on the playfield. Then set your cursor over the part. There's a complete list of Handles below.\n"
    "\n"
    "RECYCLE HANDLE\n"
    "Click on the trash can to put the part back in the Parts Bin.\n"
    "\n"
    "FLIP HANDLE\n"
    "These curved arrows allow you to flip the part. Some parts can be flipped several different ways.\n"
    "\n"
    "SIZE HANDLE\n"
    "This double arrow means the part can be stretched or shrunk when you click on the arrow and drag the cursor. Click the cursor a second time when the part has been stretched to the designated length.\n"
    "\n"
    "INFO HANDLE\n"
    "This magnifying glass handle gives you information about any part, including how the part works and ways of using it."
    "\n Beware that not every object is movable or interactable in the level, only those which are part of the solution!"
    "\n Also keep in mind that your answers should be precise as there is a cap of 400 characters per response."
)